### ISSUE TITLE
Disk Error in hardware boot

### ISSUE THREAD

**Issue by elsaversailles** [jdah/tetris-os#42]
I flash the image using Balena etcher, boot into it but encountered an error.

TETRIS TIME
DISK ERROR
C

**Comment by zment4** [comment]
This is most probably because the bootloader uses INT13h AH=42h, which is an LBA addressing mode for hard disks, but your computer wants to read it with CHS instead. I'm in the process of modifying the bootloader to have both LBA and CHS addressing, but my confidence on having enough motivation to get it working is not through the roof right now so don't hold your breath.

**Comment by jdah** [comment]
@zment4 I think INT 13h AH=02h would be a fine drop in replacement in the bootloader for CHS addressing - I will see if I can get it working myself.

**Comment by Doridian** [comment]
> @zment4 I think INT 13h AH=02h would be a fine drop in replacement in the bootloader for CHS addressing - I will see if I can get it working myself.

I have tried that this weekend. Using 13h 08h to read the drive's parameters.
I got it to read...something...sadly not a working tetris-os xD

**Comment by zment4** [comment]
I got it working with CHS reads! 

I'll clean it up and do combined LBA/CHS read to use LBA first and then CHS if that fails. I also read the geometry data with AH=08h.

**Comment by Doridian** [comment]
> I got it working with CHS reads!
> 
> I'll clean it up and do combined LBA/CHS read to use LBA first and then CHS if that fails. I also read the geometry data with AH=08h.
> 
> EDIT: The biggest problems I've been having is the GAS syntax, I keep mixing which way the source and destination go.

I for sure gotta read your code to see where I went wrong with computing stuff...
This is my first project actually dealing with bootloaders and I've been cross-referencing wikipedia and osdev and googling too much, now I forgot what comes from where xD

**Comment by jdah** [comment]
> I got it working with CHS reads!
> I'll clean it up and do combined LBA/CHS read to use LBA first and then CHS if that fails. I also read the geometry data with AH=08h.

Awesome! excited to see it.

> EDIT: The biggest problems I've been having is the GAS syntax, I keep mixing which way the source and destination go.
 
\>:(

**Comment by Doridian** [comment]
> 
> > EDIT: The biggest problems I've been having is the GAS syntax, I keep mixing which way the source and destination go.
> 
> >:(

Actually, that messed me up at first as well.
I was like "mov dest, src", wait, this code makes no sense
Granted, it makes more sense if you're just reading it to write "mov src, dest" and "add imm,reg" but...when you have some assembly knowledge, it can be a bit confusing xD

**Comment by zment4** [comment]
Yeah I had the code basically done about 6 hours ago, but for that time I've been mostly setting up debug environments etc. to try to figure out why I'm not getting it. Turns out that AL didn't have the correct number of sectors when comparing with current sector because instead of reading from memory, I wrote there. 

> >:(

Hey, not hating here or anything, the order just doesn't come naturally to me. Just a case of "what you are used to" and this happened to trip me up this time. :)

**Comment by jdah** [comment]
Just joking of course :) will take a look at the PR, thanks @zment4 !

**Comment by bence98** [comment]
I just built `zment4:chs_reads_pr`, unfortunately it just bootloops. Same thing happens with my code: https://github.com/bence98/tetris-os/tree/int02h
`Doridian:floppy-bootloader` prints out a lot of junk, but otherwise just does the same bootloop.
I tested zment4's code on bare metal, plus all three branches with:
```
qemu-system-i386 -fda boot.iso
```
Plus, I tested my own code with `qemu-system-x86_64`. Always the same: bootloop.
At this point, I've wasted like 3 hours... :/ I have school tomorrow... Hopefully you smarter people will figure it out. :)

Oh, and +1 for hating the GAS syntax, with the god-forsaken %s and $s and `source, destination`s and `movw` instead of `mov word`/`mov` (the number of times I typed `mowv`...) and all... Sigh.

**Comment by bence98** [comment]
Ok, I won't bother writing it to diskette yet, then :D

**Comment by zment4** [comment]
Bootloops in my experience mean the data from the media was not transfered completely or in the correct order to the memory. I had those if I mixed up my sector/head increase counters. @bence98 You could try the release on my fork. https://github.com/zment4/tetris-os/tree/chs_dynSB16v1 ? This binary has been tested on 3 different systems. Not on a floppy though. I could actually do that right now...

**Comment by bence98** [comment]
Release binary boots in Qemu, now writing to diskette. Almost overwrote main partition with `dd`. I should go to sleep... -.-

**Comment by zment4** [comment]
> Release binary boots in Qemu, now writing to diskette. Almost overwrote main partition with `dd`. I should go to sleep... -.-

Ooohhhh I'm glad you didn't mistype!

**Comment by zment4** [comment]
> Too bad I only have one "authentic" floppy drive, in my tower PC, with which I test the finished disks...

 I got rid of all of my diskette drives like years ago, and now I'm kinda regretting that decision as I'm getting more into retro stuff again. At least you got authentic floppy drives! Looked up and new ones even from China cost like 40€ or something.

> Tetris OS my main "daily driver" OS :D

Oh. My. God. That sounds like a dystopian purgatory or something. 😱

**Comment by zment4** [comment]
Boot loops on the PR #44  might've been an errant JNE (that isn't found anywhere else, so that's weird, I don't remember changing that). It's been fixed now as is now the same as my forks binary release. Thanks to @Doridian for pointing that out to me!

**Comment by jdah** [comment]
#44 has now been incorporated into the code base (thanks @zment4 !), this still broken for anyone?

**Comment by Naheel-Azawy** [comment]
> #44 has now been incorporated into the code base (thanks @zment4 !), this still broken for anyone?

Just pulled the latest changes, `dd`ed to a usb drive, and booted using my Lenovo Z41. Yep, still, the same disk error.

**Comment by zment4** [comment]
> Just pulled the latest changes, `dd`ed to a usb drive, and booted using my Lenovo Z41. Yep, still, the same disk error.

Hmm. I think jdh needs to pull one of the error code showing mods to get this further. It could be a number of things - for instance my wife's computer couldn't read past the 1142th sector in CHS mode, for some reason, and the error code was just 01, meaning invalid parameters. Read more, get the same error, read less, everything works.

Or if you want to wait enough I could setup a build to try with error codes - I can't remember if the build in my fork has them currently enabled or not, but it's not a big deal to make then available, just takes some time.

**Comment by Naheel-Azawy** [comment]
@zment4 I guess I can wait :)
I'm busy with few other stuff so I might disappear for a while anyway.

**Comment by zment4** [comment]
> @zment4 I guess I can wait :)
> I'm busy with few other stuff so I might disappear for a while anyway.

Ah, sorry it took so long, I just checked and the PC Speaker release in my fork should print dots for each sector it loads, and prints out the error code as a hex value on screen if a DISK ERROR happens. If you try to run with that, knowing how many dots it printed out and what the hex error code was might give some clues as to what is happening there.

**Comment by Naheel-Azawy** [comment]
@zment4 I quickly downloaded the source of your release, `make bin`, `dd`ed, the image and still the same disk error with nothing else. No dots nor hex error. I don't know why but I `dd`ed zeros to my bootable usb and then the image bin again. Still, same disk error.
At this point I'm suspecting that maybe it's me who's doing something wrong. But I might come back to this later

**Comment by zment4** [comment]
> @zment4 I quickly downloaded the source of your release, `make bin`, `dd`ed, the image and still the same disk error with nothing else. No dots nor hex error. I don't know why but I `dd`ed zeros to my bootable usb and then the image bin again. Still, same disk error.
> At this point I'm suspecting that maybe it's me who's doing something wrong. But I might come back to this later

Did you try the prebuilt boot.bin file? Do you get TETRIS TIME, and then DISK ERROR? If so, if you are using my build/release source, it should at least print a hex value before DISK ERROR to let you know the error code. It's weird that it doesn't.

**Comment by elsaversailles** [comment]
The patch .img already worked for me :) thanks but on the menu there's a quick flash of code below:

Failed to reset sb16: 255

What does this mean? Also I didn't hear any audio, though its ok for me since I can play. Pretty nifty. Thanks again

**Comment by elsaversailles** [comment]
![Uploading IMG20210508122721.jpg…]()

**Comment by zment4** [comment]
> Failed to reset sb16: 255

It just means the code is trying to access an SB16 but couldn't find one, thus reverts to no sound so it can still be played. This means either you are running on real hardware with no SB16 installed with the settings TETRIS-OS uses, or that you run it as in image with some emulator/virtualization like qemu or VirtualBox and didn't have the SB16 sound device configured correctly and/or enabled.

**Comment by elsaversailles** [comment]
> > Failed to reset sb16: 255
> 
> It just means the code is trying to access an SB16 but couldn't find one, thus reverts to no sound so it can still be played. This means either you are running on real hardware with no SB16 installed with the settings TETRIS-OS uses, or that you run it as in image with some emulator/virtualization like qemu or VirtualBox and didn't have the SB16 sound device configured correctly and/or enabled.

I see, yeah 'm running on a real hardware :)

**Comment by Naheel-Azawy** [comment]
> Did you try the prebuilt boot.bin file? Do you get TETRIS TIME, and then DISK ERROR? If so, if you are using my build/release source, it should at least print a hex value before DISK ERROR to let you know the error code. It's weird that it doesn't.

Hello again @zment4, sorry it took me a while. Last time I tried it in rush and I wasn't sure if I did something wrong.
Today I tried again and still I'm getting that same "TETRIS TIME, and then DISK ERROR" but with no hex value.
I am using your release source "tetris-os-pcspkr_v1.tar.gz" but not the prebuilt "boot.bin". I'm not a big fan of binaries. But I assume it should be compiled from the same source you have on that release.

**Comment by zment4** [comment]
> I am using your release source "tetris-os-pcspkr_v1.tar.gz" but not the prebuilt "boot.bin". I'm not a big fan of binaries. But I assume it should be compiled from the same source you have on that release.

I just checked the code from that release, and yes, it does have a "print hex" call before "print disk error".

```
disk_error:
    mov %ah, %al
    call print_hex

    movw $disk_error_str, %si
    call print 
```

I have no idea why you aren't getting an error code onscreen. I'm grasping at straws here, but are you sure you wrote the correct image file to your boot medium? My forks pcspkr release makes it a boot.bin instead boot.iso or boot.img. I really don't know what else could be going on, sorry!

**Comment by Naheel-Azawy** [comment]
Yeah I did realize it's boot.bin and I did try to write the image multiple times. No need to apologize I don't know what's happening either. This probably means I'm doing something wrong somewhere. So no worries, I might figure it out sometime later. Thank you for the cool stuff.
